version: '3'

services:
  db:
    image: postgres
    env_file:
      .env
    volumes:
      - final_edu_pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    tty: true
    command: sh -c "sleep 10 && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  final_edu_pg_data: