# Generated by Django 5.0 on 2023-12-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalmodule',
            options={'verbose_name': 'Модуль', 'verbose_name_plural': 'Модуля'},
        ),
        migrations.AlterField(
            model_name='educationalmodule',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='порядковый номер'),
        ),
    ]
