# Generated by Django 5.0 on 2023-12-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_educationalmodule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalmodule',
            name='number',
        ),
    ]
